### ISSUE TITLE
Page build fail

### ISSUE THREAD

**Issue by rowo** [onaio/blog#48] opened 2016-03-07 20:06 UTC
Copied an old post and still got a page build fail:

**Email received:**

The page build failed with the following error:

Page build failed. For more information, see https://help.github.com/articles/troubleshooting-github-pages-build-failures.

GitHub Pages was recently upgraded to Jekyll 3.0. It may help to confirm you're using the correct dependencies:

  https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0

If you have any questions you can contact us by replying to this email.

**Comment by okal** [comment] 2016-03-09 06:44
Fails for me running Jekyll 3, so that might have something to do with it. Can you share the email, @rowo? The actual failure. Or is the above the full text of it?

**Comment by rowo** [comment] 2016-03-09 11:48
What is above is the full text. It did not indicate a specific error.

**Comment by okal** [comment] 2016-03-09 12:40
It seems there was a problem with the authors.yml. Do you see what you expect now on blog.ona.io?

**Comment by okal** [comment] 2016-03-09 12:49
You can close this if the issue is resolved. I pushed directly to gh-pages :astonished: Sorry about that.

**Closed** 2016-03-09 12:50 UTC
Labels: bug

**Comment by rowo** [comment] 2016-03-09 13:15
cool thanks.
